TARGET		:= test_sort
CSRCS		:= $(TARGET).c

CSRCS		+= bubblesort.c
CSRCS		+= heapsort.c
CSRCS		+= insertionsort.c
CSRCS		+= mergesort.c
CSRCS		+= quicksort.c
CSRCS		+= radixsort.c
CSRCS		+= selectionsort.c
CSRCS		+= shellsort.c

include ../../prj_native.mk
